### ISSUE TITLE
Class 'MainMenuManager' not found.

### ISSUE THREAD

**Issue by Wizsensei** [JasonHuang3D/DragonCliffMod#1]
Sorry i managed setup with unity manager and installed mod with zip file via mod manager but when i open game in mod menu (ctrl f10) mod list i get mods but with error in log says 
[Mod_AutoUtils] Version '1.1.4'. Loading.
[Mod_AutoUtils] [Error] File 'C:\Users\XXX\Desktop\Dragon.Cliff.v13.08.2019\CSharpMods\Mods\Mod_AutoUtils.dll' not found.
[Mod_AutoUtils] Loading time 0.00 s.
[Manager] FINISH. SUCCESSFUL LOADED 0/1 MODS.
Can you help pls i dont realyy understand this kind of things xD

**Comment by JasonHuang3D** [comment]
Hi wizsensei, the unity mod manager is a tool to automatically install mods into the game directory. it appears that the Mod_AutoUtils is either not installed correctly or some system threads blocked the installing process. Please following the steps below:
1) Extract all contents from Mod_AutoUtils.zip in to a folder named "Mod_AutoUtils".
2) Under your game directory root which contains "game.exe" you may find a folder named  "CSharpMods", if the folder does not exist, create it manually.
3) Copy the folder from step one into "CSharpMods" folder from step two.
